version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    container_name: node_container
    depends_on:
      - mongodb
    ports:
      - 3000:3000  
    environment:
      PORT: 3000
      DATABASE_URL: "mongodb+srv://amansharma:amansharma@cluster0.ctqsdwb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      SECRET: "AMANSHARMAISSECRET"
    volumes:
      - .:/app
volumes:
  mongo_db: {}
