# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node-js Practice

on:
  push:
    branches : [main]

jobs:
  build:
  
   runs-on: unbuntu-latest

   strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
   steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
